# Generated by Django 2.2.3 on 2019-07-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummy',
            name='background_height',
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='background_transparent',
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='background_width',
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='content',
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='x_pos',
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='y_pos',
        ),
        migrations.RemoveField(
            model_name='king',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='king',
            name='background_transparent',
        ),
        migrations.RemoveField(
            model_name='king',
            name='content',
        ),
        migrations.RemoveField(
            model_name='king',
            name='display_device_id',
        ),
        migrations.RemoveField(
            model_name='king',
            name='display_stb_id',
        ),
        migrations.RemoveField(
            model_name='king',
            name='font_color',
        ),
        migrations.RemoveField(
            model_name='king',
            name='y_pos',
        ),
    ]
